# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 802)
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 30, 681, 391))
        self.lcdNumber.setStatusTip("")
        self.lcdNumber.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 0);\n"
"background-color: rgb(0, 0, 127);")
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setEnabled(False)
        self.spinBox.setGeometry(QtCore.QRect(680, 30, 411, 191))
        self.spinBox.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 0);\n"
"font: 75 120pt \"Adobe Arabic\";\n"
"background-color: rgb(0, 0, 127);")
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setSpecialValueText("")
        self.spinBox.setMaximum(999999)
        self.spinBox.setSingleStep(10)
        self.spinBox.setProperty("value", 60)
        self.spinBox.setObjectName("spinBox")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setEnabled(True)
        self.lcdNumber_2.setGeometry(QtCore.QRect(681, 220, 307, 201))
        self.lcdNumber_2.setStyleSheet("font: 75 72pt \"Adobe Arabic\";\n"
"color: rgb(255, 255, 0);\n"
"background-color: rgb(85, 85, 255);\n"
"background-color: rgb(0, 0, 127);")
        self.lcdNumber_2.setDigitCount(6)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setGeometry(QtCore.QRect(680, 420, 411, 191))
        self.spinBox_2.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 0);\n"
"font: 75 100pt \"Adobe Arabic\";\n"
"background-color: rgb(0, 0, 127);")
        self.spinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setSpecialValueText("")
        self.spinBox_2.setMaximum(8000)
        self.spinBox_2.setSingleStep(500)
        self.spinBox_2.setProperty("value", 800)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setEnabled(False)
        self.spinBox_3.setGeometry(QtCore.QRect(680, 610, 411, 191))
        self.spinBox_3.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 75 100pt \"Adobe Arabic\";\n"
"color: rgb(255, 255, 0);\n"
"background-color: rgb(85, 85, 255);\n"
"background-color: rgb(0, 0, 127);")
        self.spinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setSpecialValueText("")
        self.spinBox_3.setMaximum(1500)
        self.spinBox_3.setSingleStep(10)
        self.spinBox_3.setProperty("value", 850)
        self.spinBox_3.setObjectName("spinBox_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(-1, 462, 681, 341))
        self.textBrowser.setStyleSheet("font: 14pt \"黑体\";\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(690, 620, 171, 41))
        self.checkBox.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 61, 31))
        self.label.setStyleSheet("font: 75 16pt \"Adobe Arabic\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 240, 161, 31))
        self.label_3.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 430, 91, 31))
        self.label_5.setStyleSheet("font: 75 14pt \"Adobe Arabic\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 1091, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setStyleSheet("font: 75 14pt \"Adobe Arabic\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setStyleSheet("font: 75 14pt \"Adobe Arabic\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setStyleSheet("font: 75 14pt \"Adobe Arabic\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setStyleSheet("font: 75 14pt \"Adobe Arabic\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_11.setStyleSheet("font: 75 14pt \"Adobe Arabic\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_15 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_15.setEnabled(True)
        self.pushButton_15.setStyleSheet("font: 75 14pt \"Adobe Arabic\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout.addWidget(self.pushButton_15)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(690, 40, 131, 41))
        self.label_2.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(0, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(690, 420, 131, 61))
        self.label_4.setStyleSheet("font: 16pt \"宋体\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(989, 30, 111, 91))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QtCore.QRect(990, 124, 111, 91))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setGeometry(QtCore.QRect(990, 420, 111, 91))
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setGeometry(QtCore.QRect(989, 516, 111, 91))
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setGeometry(QtCore.QRect(990, 610, 111, 91))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setGeometry(QtCore.QRect(989, 705, 111, 91))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 401, 681, 20))
        self.label_6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(420, 280, 361, 251))
        self.widget.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"background-color: rgb(179, 203, 255);")
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 80, 130, 30))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(6, 80, 131, 40))
        self.label_7.setStyleSheet("font: 75 11pt \"Adobe Arabic\";")
        self.label_7.setObjectName("label_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setGeometry(QtCore.QRect(280, 80, 75, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 140, 130, 30))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 131, 40))
        self.label_8.setStyleSheet("font: 75 11pt \"Adobe Arabic\";")
        self.label_8.setObjectName("label_8")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setGeometry(QtCore.QRect(190, 220, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setGeometry(QtCore.QRect(280, 220, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(110, 40, 201, 41))
        self.label_9.setStyleSheet("font: 75 14pt \"Adobe Arabic\";")
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lcdNumber.setToolTip(_translate("MainWindow", "hello"))
        self.checkBox.setText(_translate("MainWindow", "设置高压/V"))
        self.label.setText(_translate("MainWindow", "计数值"))
        self.label_3.setText(_translate("MainWindow", "已测时间/Sec"))
        self.label_5.setText(_translate("MainWindow", "状态栏"))
        self.pushButton.setText(_translate("MainWindow", "定标器连接"))
        self.pushButton_2.setText(_translate("MainWindow", "开始"))
        self.pushButton_3.setText(_translate("MainWindow", "停止"))
        self.pushButton_4.setText(_translate("MainWindow", "复位"))
        self.pushButton_11.setText(_translate("MainWindow", "设定高压最大值"))
        self.pushButton_15.setText(_translate("MainWindow", "帮助文档"))
        self.label_2.setText(_translate("MainWindow", "测量时间/Sec"))
        self.label_4.setText(_translate("MainWindow", "测量阈/mV"))
        self.label_7.setText(_translate("MainWindow", "请输入管理员密码："))
        self.pushButton_12.setText(_translate("MainWindow", "登录"))
        self.label_8.setText(_translate("MainWindow", "设定高压最大值/V："))
        self.pushButton_13.setText(_translate("MainWindow", "确定"))
        self.pushButton_14.setText(_translate("MainWindow", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

